# Generated by Django 5.0 on 2023-12-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='time_zone',
            field=models.CharField(blank=True, choices=[('AUSWEST', 'Australian Western Standard Time'), ('ASUSCR', 'Australian Central Standard Time'), ('AUSEST', 'Australian Eastern Standard Time')], max_length=100, null=True),
        ),
    ]
