# Generated by Django 5.0 on 2024-01-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_mediagallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='calendar',
            name='days_of_week',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.dayofweek'),
        ),
    ]
