# Generated by Django 5.0 on 2024-01-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_calendar_days_of_week_calendar_days_of_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='end_date',
            new_name='custom_end_date',
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='start_date',
            new_name='custom_start_date',
        ),
        migrations.AddField(
            model_name='calendar',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
