# Generated by Django 5.0 on 2023-12-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_myapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('tutor', 'tutor'), ('student', 'student')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_zone',
            field=models.CharField(blank=True, choices=[('AWST', 'Australian Western Standard Time'), ('ACST', 'Australian Central Standard Time'), ('AEST', 'Australian Eastern Standard Time')], max_length=100, null=True),
        ),
    ]
