---
#= Dev
#===================================================
- hosts: dev
  vars_files:
    - vars.yml
  gather_facts: false
  become: true
  become_method: sudo

  roles:
    - common
    - nginx
    - postgresql
    - project_data
    - redis
    - celery

#= Production
#===================================================
- hosts: prod
  vars_files:
    - vars.yml
  gather_facts: false
  become: true
  become_method: sudo

  roles:
    - common
    - nginx
    - project_data
    - redis
    - celery
